(function () {
  "use strict";

  const ACCESS_DATE = "accessed-2026-10-04";
  const CURRENT_ACCESS_DATE = "accessed-2026-10-05";
  const GOOGLE_CLOUD_DOCS_LICENSE = "CC BY 4.0";

  function googleCloudSource(name, url, accessDate = ACCESS_DATE) {
    return Object.freeze({
      name: `Google Cloud documentation: ${name}`,
      url,
      commit: accessDate,
      license: GOOGLE_CLOUD_DOCS_LICENSE
    });
  }

  globalThis.PCA_QUIZ_SOURCES = Object.freeze({
    EXAM_GUIDE: googleCloudSource(
      "Professional Cloud Architect exam guide",
      "https://cloud.google.com/learn/certification/cloud-architect"
    ),
    CLOUD_RUN: googleCloudSource("Cloud Run overview", "https://cloud.google.com/run/docs/overview/what-is-cloud-run"),
    GKE: googleCloudSource("Google Kubernetes Engine overview", "https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview"),
    CLOUD_SQL: googleCloudSource("Cloud SQL overview", "https://cloud.google.com/sql/docs/introduction"),
    SPANNER: googleCloudSource("Spanner overview", "https://cloud.google.com/spanner/docs/overview"),
    BIGQUERY: googleCloudSource("BigQuery overview", "https://cloud.google.com/bigquery/docs/introduction"),
    FILESTORE: googleCloudSource("Filestore overview", "https://cloud.google.com/filestore/docs/overview"),
    CLOUD_STORAGE: googleCloudSource("Cloud Storage overview", "https://cloud.google.com/storage/docs/introduction"),
    STORAGE_CLASSES: googleCloudSource("Cloud Storage classes", "https://cloud.google.com/storage/docs/storage-classes"),
    STORAGE_LIFECYCLE: googleCloudSource("Cloud Storage lifecycle management", "https://cloud.google.com/storage/docs/lifecycle"),
    BUCKET_LOCK: googleCloudSource("Cloud Storage Bucket Lock", "https://cloud.google.com/storage/docs/bucket-lock"),
    PUBSUB: googleCloudSource("Pub/Sub overview", "https://cloud.google.com/pubsub/docs/overview"),
    SHARED_VPC: googleCloudSource("Shared VPC", "https://cloud.google.com/vpc/docs/shared-vpc"),
    INTERCONNECT: googleCloudSource("Cloud Interconnect overview", "https://cloud.google.com/network-connectivity/docs/interconnect/concepts/overview"),
    VPN: googleCloudSource("Cloud VPN overview", "https://cloud.google.com/network-connectivity/docs/vpn/concepts/overview"),
    LOAD_BALANCING: googleCloudSource("Cloud Load Balancing overview", "https://cloud.google.com/load-balancing/docs/load-balancing-overview"),
    RESOURCE_HIERARCHY: googleCloudSource("resource hierarchy", "https://cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy"),
    IAM: googleCloudSource("Identity and Access Management overview", "https://cloud.google.com/iam/docs/overview"),
    SERVICE_ACCOUNTS: googleCloudSource("service accounts overview", "https://cloud.google.com/iam/docs/service-account-overview"),
    ORGANIZATION_POLICY: googleCloudSource("Organization Policy overview", "https://cloud.google.com/resource-manager/docs/organization-policy/overview"),
    MANAGED_INSTANCE_GROUPS: googleCloudSource("managed instance groups", "https://cloud.google.com/compute/docs/instance-groups"),
    SPOT_VMS: googleCloudSource("Spot VMs", "https://cloud.google.com/compute/docs/instances/spot"),
    SECRET_MANAGER: googleCloudSource("Secret Manager overview", "https://cloud.google.com/secret-manager/docs/overview"),
    CLOUD_KMS: googleCloudSource("Cloud Key Management Service overview", "https://docs.cloud.google.com/kms/docs/key-management-service"),
    VPC_SERVICE_CONTROLS: googleCloudSource("VPC Service Controls overview", "https://cloud.google.com/vpc-service-controls/docs/overview"),
    CLOUD_ARMOR: googleCloudSource("Cloud Armor overview", "https://cloud.google.com/armor/docs/cloud-armor-overview"),
    AUDIT_LOGS: googleCloudSource("Cloud Audit Logs overview", "https://cloud.google.com/logging/docs/audit"),
    SENSITIVE_DATA_PROTECTION: googleCloudSource("Sensitive Data Protection overview", "https://docs.cloud.google.com/sensitive-data-protection/docs/sensitive-data-protection-overview"),
    WORKLOAD_IDENTITY: googleCloudSource("Workload Identity Federation for GKE", "https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity"),
    IAP: googleCloudSource("Identity-Aware Proxy overview", "https://cloud.google.com/iap/docs/concepts-overview"),
    UNIFORM_BUCKET_ACCESS: googleCloudSource("uniform bucket-level access", "https://cloud.google.com/storage/docs/uniform-bucket-level-access"),
    BILLING_BUDGETS: googleCloudSource("Cloud Billing budgets", "https://cloud.google.com/billing/docs/how-to/budgets"),
    COMPUTE_CUDS: googleCloudSource("Compute Engine committed use discounts", "https://cloud.google.com/compute/docs/instances/committed-use-discounts-overview"),
    RECOMMENDER: googleCloudSource("Recommender overview", "https://cloud.google.com/recommender/docs/overview"),
    BIGQUERY_COSTS: googleCloudSource("BigQuery cost best practices", "https://cloud.google.com/bigquery/docs/best-practices-costs"),
    BILLING_EXPORT: googleCloudSource("Cloud Billing data export to BigQuery", "https://cloud.google.com/billing/docs/how-to/export-data-bigquery"),
    RESOURCE_LABELS: googleCloudSource("resource labels", "https://cloud.google.com/resource-manager/docs/creating-managing-labels"),
    NETWORK_SERVICE_TIERS: googleCloudSource("Network Service Tiers overview", "https://cloud.google.com/network-tiers/docs/overview"),
    SERVICE_MONITORING: googleCloudSource("service monitoring concepts", "https://cloud.google.com/monitoring/service-monitoring"),
    CLOUD_BUILD: googleCloudSource("Cloud Build overview", "https://cloud.google.com/build/docs/overview"),
    CLOUD_DEPLOY: googleCloudSource("Cloud Deploy overview", "https://cloud.google.com/deploy/docs/overview"),
    CLOUD_RUN_TRAFFIC: googleCloudSource("Cloud Run traffic migration and rollbacks", "https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration"),
    DATABASE_MIGRATION: googleCloudSource("Database Migration Service overview", "https://cloud.google.com/database-migration/docs/overview"),
    CLOUD_SCHEDULER: googleCloudSource("Cloud Scheduler overview", "https://cloud.google.com/scheduler/docs/overview"),
    DISASTER_RECOVERY: googleCloudSource("disaster recovery planning guide", "https://cloud.google.com/architecture/dr-scenarios-planning-guide"),
    CLOUD_SQL_HA: googleCloudSource("Cloud SQL high availability", "https://cloud.google.com/sql/docs/mysql/high-availability"),
    UPTIME_CHECKS: googleCloudSource("Cloud Monitoring uptime checks", "https://cloud.google.com/monitoring/uptime-checks"),
    BIGTABLE_SCHEMA: googleCloudSource("Bigtable schema design best practices", "https://cloud.google.com/bigtable/docs/schema-design"),
    DATAFLOW_STREAMING: googleCloudSource("Dataflow streaming pipelines", "https://cloud.google.com/dataflow/docs/concepts/streaming-pipelines"),
    ALLOYDB: googleCloudSource("AlloyDB overview", "https://cloud.google.com/alloydb/docs/overview"),
    PRIVATE_SERVICE_CONNECT: googleCloudSource("Private Service Connect", "https://cloud.google.com/vpc/docs/private-service-connect"),
    HA_VPN_INTERCONNECT: googleCloudSource("HA VPN over Cloud Interconnect", "https://cloud.google.com/network-connectivity/docs/interconnect/concepts/ha-vpn-interconnect"),
    HIERARCHICAL_FIREWALL: googleCloudSource("hierarchical firewall policies", "https://cloud.google.com/firewall/docs/firewall-policies"),
    PRIVATE_GOOGLE_ACCESS_HYBRID: googleCloudSource("Private Google Access for on-premises hosts", "https://cloud.google.com/vpc/docs/configure-private-google-access-hybrid"),
    WORKFORCE_IDENTITY: googleCloudSource("Workforce Identity Federation", "https://cloud.google.com/iam/docs/workforce-identity-federation"),
    WORKLOAD_IDENTITY_FEDERATION: googleCloudSource("Workload Identity Federation", "https://cloud.google.com/iam/docs/workload-identity-federation"),
    KMS_SEPARATION_DUTIES: googleCloudSource("Cloud KMS separation of duties", "https://cloud.google.com/kms/docs/separation-of-duties"),
    VPC_SC_DRY_RUN: googleCloudSource("VPC Service Controls dry run mode", "https://cloud.google.com/vpc-service-controls/docs/dry-run-mode"),
    AGGREGATED_LOG_SINKS: googleCloudSource("aggregated log sinks", "https://cloud.google.com/logging/docs/export/aggregated_sinks"),
    BIGQUERY_SLOTS: googleCloudSource("BigQuery slots", "https://cloud.google.com/bigquery/docs/slots"),
    BIGQUERY_MATERIALIZED_VIEWS: googleCloudSource("BigQuery materialized views", "https://cloud.google.com/bigquery/docs/materialized-views-use"),
    CLOUD_BUILD_PRIVATE_POOLS: googleCloudSource("Cloud Build private pools", "https://cloud.google.com/build/docs/private-pools/private-pools-overview"),
    BINARY_AUTHORIZATION: googleCloudSource("Binary Authorization overview", "https://cloud.google.com/binary-authorization/docs/overview"),
    STORAGE_AVAILABILITY: googleCloudSource("Cloud Storage availability and durability", "https://cloud.google.com/storage/docs/availability-durability"),
    CLOUD_SQL_PITR: googleCloudSource("Cloud SQL point-in-time recovery", "https://cloud.google.com/sql/docs/postgres/backup-recovery/restore"),
    PUBSUB_EXACTLY_ONCE: googleCloudSource("Pub/Sub exactly-once delivery", "https://cloud.google.com/pubsub/docs/exactly-once-delivery"),
    CLOUD_TASKS_COMPARISON: googleCloudSource("choosing Cloud Tasks or Pub/Sub", "https://cloud.google.com/tasks/docs/comp-pub-sub"),
    SERVERLESS_SPARK: googleCloudSource("Managed Service for Apache Spark serverless overview", "https://cloud.google.com/dataproc-serverless/docs/overview"),
    GKE_MODES: googleCloudSource("GKE modes of operation", "https://cloud.google.com/kubernetes-engine/docs/concepts/choose-cluster-mode"),
    SPANNER_CONFIGURATIONS: googleCloudSource("Spanner instance configurations", "https://cloud.google.com/spanner/docs/instance-configurations"),
    APIGEE: googleCloudSource("Apigee overview", "https://cloud.google.com/apigee/docs/api-platform/get-started/what-apigee"),
    INFRASTRUCTURE_MANAGER: googleCloudSource("Infrastructure Manager overview", "https://cloud.google.com/infrastructure-manager/docs/overview"),
    MIG_ROLLING_UPDATES: googleCloudSource("managed instance group rolling updates", "https://cloud.google.com/compute/docs/instance-groups/rolling-out-updates-to-managed-instance-groups"),
    NETWORK_CONNECTIVITY_CENTER: googleCloudSource("Network Connectivity Center overview", "https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/overview"),
    IAM_DENY: googleCloudSource("IAM deny policies", "https://cloud.google.com/iam/docs/deny-overview"),
    ACCESS_TRANSPARENCY: googleCloudSource("Access Transparency overview", "https://cloud.google.com/assured-workloads/access-transparency/docs/overview"),
    ACCESS_CONTEXT_MANAGER: googleCloudSource("Access Context Manager overview", "https://cloud.google.com/access-context-manager/docs/overview"),
    CA_SERVICE_EXTERNAL_ROOT: googleCloudSource("CA Service subordinate CA from an external CA", "https://cloud.google.com/certificate-authority-service/docs/create-sub-ca-from-external-ca"),
    SLO_BURN_RATE: googleCloudSource("SLO burn-rate alerting", "https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring/alerting-on-budget-burn-rate"),
    LOG_BASED_METRICS: googleCloudSource("log-based metrics", "https://cloud.google.com/logging/docs/logs-based-metrics"),
    MIGRATE_VMS: googleCloudSource("Migrate to Virtual Machines lifecycle", "https://cloud.google.com/migrate/virtual-machines/docs/5.0/discover/lifecycle"),
    CLOUD_DEPLOY_CANARY: googleCloudSource("Cloud Deploy canary deployments", "https://cloud.google.com/deploy/docs/deployment-strategies/canary"),
    GKE_REGIONAL: googleCloudSource("GKE regional clusters", "https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters"),
    CLOUD_DNS_ROUTING: googleCloudSource("Cloud DNS routing policies and health checks", "https://cloud.google.com/dns/docs/routing-policies-overview"),
    CLOUD_SQL_DR: googleCloudSource("Cloud SQL disaster recovery", "https://cloud.google.com/sql/docs/postgres/intro-to-cloud-sql-disaster-recovery"),
    BIGQUERY_OMNI: googleCloudSource("BigQuery Omni overview", "https://cloud.google.com/bigquery/docs/omni-introduction", CURRENT_ACCESS_DATE),
    CLOUD_RUN_JOBS: googleCloudSource("Cloud Run jobs", "https://cloud.google.com/run/docs/create-jobs", CURRENT_ACCESS_DATE),
    GKE_MULTICLUSTER_GATEWAY: googleCloudSource("GKE multi-cluster Gateways", "https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-gateways", CURRENT_ACCESS_DATE),
    CLOUD_COMPOSER: googleCloudSource("Managed Service for Apache Airflow overview", "https://cloud.google.com/composer/docs/composer-3/composer-overview", CURRENT_ACCESS_DATE),
    CLOUD_RUN_VPC: googleCloudSource("Cloud Run VPC connectivity options", "https://cloud.google.com/run/docs/configuring/connecting-vpc", CURRENT_ACCESS_DATE),
    RESOURCE_TAGS: googleCloudSource("Resource Manager tags and mandatory tag enforcement", "https://cloud.google.com/resource-manager/docs/tags/tags-overview", CURRENT_ACCESS_DATE),
    VM_MANAGER_PATCH: googleCloudSource("VM Manager patching", "https://cloud.google.com/compute/vm-manager/docs/patch", CURRENT_ACCESS_DATE),
    COMPACT_PLACEMENT: googleCloudSource("compact placement policies", "https://cloud.google.com/compute/docs/instances/use-compact-placement-policies", CURRENT_ACCESS_DATE),
    CLOUD_EKM: googleCloudSource("Cloud External Key Manager", "https://cloud.google.com/kms/docs/ekm", CURRENT_ACCESS_DATE),
    ACCESS_APPROVAL: googleCloudSource("Access Approval overview", "https://cloud.google.com/assured-workloads/access-approval/docs/overview", CURRENT_ACCESS_DATE),
    SCC_ATTACK_PATHS: googleCloudSource("Security Command Center attack paths", "https://cloud.google.com/security-command-center/docs/attack-exposure-learn", CURRENT_ACCESS_DATE),
    CLOUD_SQL_IAM_AUTH: googleCloudSource("Cloud SQL IAM database authentication", "https://cloud.google.com/sql/docs/postgres/iam-authentication", CURRENT_ACCESS_DATE),
    BIGQUERY_BI_ENGINE: googleCloudSource("BigQuery BI Engine", "https://cloud.google.com/bigquery/docs/bi-engine-intro", CURRENT_ACCESS_DATE),
    CLOUD_PROFILER: googleCloudSource("Cloud Profiler overview", "https://cloud.google.com/profiler/docs/about-profiler", CURRENT_ACCESS_DATE),
    MONITORING_METRICS_SCOPE: googleCloudSource("Cloud Monitoring metrics scopes", "https://cloud.google.com/monitoring/settings/multiple-projects", CURRENT_ACCESS_DATE),
    CLOUD_DEPLOY_VERIFY: googleCloudSource("Cloud Deploy deployment verification", "https://cloud.google.com/deploy/docs/verify-deployment", CURRENT_ACCESS_DATE),
    GKE_NODE_UPGRADES: googleCloudSource("GKE node upgrade strategies", "https://cloud.google.com/kubernetes-engine/docs/concepts/node-pool-upgrade-strategies", CURRENT_ACCESS_DATE),
    CLOUD_RUN_SERVICE_HEALTH: googleCloudSource("Cloud Run cross-region service health", "https://cloud.google.com/run/docs/configuring/configure-service-health", CURRENT_ACCESS_DATE),
    PUBSUB_DEAD_LETTER: googleCloudSource("Pub/Sub dead-letter topics", "https://cloud.google.com/pubsub/docs/dead-letter-topics", CURRENT_ACCESS_DATE),
    STORAGE_SOFT_DELETE: googleCloudSource("Cloud Storage soft delete", "https://cloud.google.com/storage/docs/soft-delete", CURRENT_ACCESS_DATE)
  });
})();
